### ISSUE TITLE
cannot run 0_8_allocate_vaccine_market.R

### ISSUE THREAD

**Issue by jarawees** [jarawees/covidmodel-hitap#22]
Hi @yangclaraliu
As Siobhan mentioned in the email, we cannot get 0_8_allocate_vaccine_market.R to run as it seems to refer to seg_primary, which is in a commented-out section of 0_7_vaccine_market.R (the chunk below):
https://github.com/jarawees/covidmodel-hitap/blob/41d6d73c5101fcda77c6ae1a2aafca2b04ff348c/code/0_7_vaccine_market.R#L285-L297

However, I'm not sure whether we need 0_8_allocate_vaccine_market.R to run or not? I noticed that it wasn't loaded in 0_LoadAll.R

**Comment by yangclaraliu** [comment]
don't need `0_8_allocate_vaccine_market.R` to run anymore.
like I answered in https://github.com/jarawees/covidmodel-hitap/issues/23#issue-1752005246, differences in terms of flows into different protection level due to different vaccine products are currently implemented using `scenario3_primary` and `scenario3_booster` - these two are both generated through `0_7_3_consistent_primary_memoryless` and through `0_7_vaccine_market.R`, which are the ones called from the `0_LoadAll.R` at this point.

**Comment by jarawees** [comment]
Thank you for clarifying both issues
